### ISSUE TITLE
Errors when running npm install

### ISSUE THREAD

**Issue by marktani** [graphcool-examples/angular-apollo-todo-example#2]
![errors-install](https://cloud.githubusercontent.com/assets/1780597/18544764/7ad115b4-7b36-11e6-9d8a-f582f758d2fd.png)

**Comment by marktani** [comment]
@kamilkisiela @schickling any ideas?

**Comment by kamilkisiela** [comment]
The reason of errors that are related to Angular is that there is a new API (NgModules) so `directives` etc are not available. It means that this example is out of date with latest angular and even rxjs (12th release candidate).

**Comment by schickling** [comment]
@kamilkisiela could you please create a PR. I can also add you as a collaborator 👍

**Comment by kamilkisiela** [comment]
I can help but not until Monday.

**Comment by schickling** [comment]
I've added you as a collaborator :)
